// Code generated by ent, DO NOT EDIT.

package entityoffboarding

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the entityoffboarding type in the database.
	Label = "entity_offboarding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEntityID holds the string denoting the entity_id field in the database.
	FieldEntityID = "entity_id"
	// FieldOutcome holds the string denoting the outcome field in the database.
	FieldOutcome = "outcome"
	// FieldCustomReason holds the string denoting the custom_reason field in the database.
	FieldCustomReason = "custom_reason"
	// FieldEffectiveDate holds the string denoting the effective_date field in the database.
	FieldEffectiveDate = "effective_date"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldReactivatedAt holds the string denoting the reactivated_at field in the database.
	FieldReactivatedAt = "reactivated_at"
	// EdgeEntity holds the string denoting the entity edge name in mutations.
	EdgeEntity = "entity"
	// Table holds the table name of the entityoffboarding in the database.
	Table = "entity_offboardings"
	// EntityTable is the table that holds the entity relation/edge.
	EntityTable = "entity_offboardings"
	// EntityInverseTable is the table name for the Entity entity.
	// It exists in this package in order to avoid circular dependency with the "entity" package.
	EntityInverseTable = "entities"
	// EntityColumn is the table column denoting the entity relation/edge.
	EntityColumn = "entity_id"
)

// Columns holds all SQL columns for entityoffboarding fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEntityID,
	FieldOutcome,
	FieldCustomReason,
	FieldEffectiveDate,
	FieldNotes,
	FieldReactivatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CustomReasonValidator is a validator for the "custom_reason" field. It is called by the builders before save.
	CustomReasonValidator func(string) error
	// NotesValidator is a validator for the "notes" field. It is called by the builders before save.
	NotesValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Outcome defines the type for the "outcome" enum field.
type Outcome string

// Outcome values.
const (
	OutcomeSold     Outcome = "sold"
	OutcomeDonated  Outcome = "donated"
	OutcomeDisposed Outcome = "disposed"
	OutcomeRecycled Outcome = "recycled"
	OutcomeLost     Outcome = "lost"
	OutcomeCustom   Outcome = "custom"
)

func (o Outcome) String() string {
	return string(o)
}

// OutcomeValidator is a validator for the "outcome" field enum values. It is called by the builders before save.
func OutcomeValidator(o Outcome) error {
	switch o {
	case OutcomeSold, OutcomeDonated, OutcomeDisposed, OutcomeRecycled, OutcomeLost, OutcomeCustom:
		return nil
	default:
		return fmt.Errorf("entityoffboarding: invalid enum value for outcome field: %q", o)
	}
}

// OrderOption defines the ordering options for the EntityOffboarding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEntityID orders the results by the entity_id field.
func ByEntityID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntityID, opts...).ToFunc()
}

// ByOutcome orders the results by the outcome field.
func ByOutcome(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutcome, opts...).ToFunc()
}

// ByCustomReason orders the results by the custom_reason field.
func ByCustomReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomReason, opts...).ToFunc()
}

// ByEffectiveDate orders the results by the effective_date field.
func ByEffectiveDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveDate, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByReactivatedAt orders the results by the reactivated_at field.
func ByReactivatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReactivatedAt, opts...).ToFunc()
}

// ByEntityField orders the results by entity field.
func ByEntityField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEntityStep(), sql.OrderByField(field, opts...))
	}
}
func newEntityStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EntityInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EntityTable, EntityColumn),
	)
}
