// Code generated by ent, DO NOT EDIT.

package entityoffboarding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldUpdatedAt, v))
}

// EntityID applies equality check predicate on the "entity_id" field. It's identical to EntityIDEQ.
func EntityID(v uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldEntityID, v))
}

// CustomReason applies equality check predicate on the "custom_reason" field. It's identical to CustomReasonEQ.
func CustomReason(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldCustomReason, v))
}

// EffectiveDate applies equality check predicate on the "effective_date" field. It's identical to EffectiveDateEQ.
func EffectiveDate(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldEffectiveDate, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldNotes, v))
}

// ReactivatedAt applies equality check predicate on the "reactivated_at" field. It's identical to ReactivatedAtEQ.
func ReactivatedAt(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldReactivatedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLTE(FieldUpdatedAt, v))
}

// EntityIDEQ applies the EQ predicate on the "entity_id" field.
func EntityIDEQ(v uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldEntityID, v))
}

// EntityIDNEQ applies the NEQ predicate on the "entity_id" field.
func EntityIDNEQ(v uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNEQ(FieldEntityID, v))
}

// EntityIDIn applies the In predicate on the "entity_id" field.
func EntityIDIn(vs ...uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIn(FieldEntityID, vs...))
}

// EntityIDNotIn applies the NotIn predicate on the "entity_id" field.
func EntityIDNotIn(vs ...uuid.UUID) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotIn(FieldEntityID, vs...))
}

// OutcomeEQ applies the EQ predicate on the "outcome" field.
func OutcomeEQ(v Outcome) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldOutcome, v))
}

// OutcomeNEQ applies the NEQ predicate on the "outcome" field.
func OutcomeNEQ(v Outcome) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNEQ(FieldOutcome, v))
}

// OutcomeIn applies the In predicate on the "outcome" field.
func OutcomeIn(vs ...Outcome) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIn(FieldOutcome, vs...))
}

// OutcomeNotIn applies the NotIn predicate on the "outcome" field.
func OutcomeNotIn(vs ...Outcome) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotIn(FieldOutcome, vs...))
}

// CustomReasonEQ applies the EQ predicate on the "custom_reason" field.
func CustomReasonEQ(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldCustomReason, v))
}

// CustomReasonNEQ applies the NEQ predicate on the "custom_reason" field.
func CustomReasonNEQ(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNEQ(FieldCustomReason, v))
}

// CustomReasonIn applies the In predicate on the "custom_reason" field.
func CustomReasonIn(vs ...string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIn(FieldCustomReason, vs...))
}

// CustomReasonNotIn applies the NotIn predicate on the "custom_reason" field.
func CustomReasonNotIn(vs ...string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotIn(FieldCustomReason, vs...))
}

// CustomReasonGT applies the GT predicate on the "custom_reason" field.
func CustomReasonGT(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGT(FieldCustomReason, v))
}

// CustomReasonGTE applies the GTE predicate on the "custom_reason" field.
func CustomReasonGTE(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGTE(FieldCustomReason, v))
}

// CustomReasonLT applies the LT predicate on the "custom_reason" field.
func CustomReasonLT(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLT(FieldCustomReason, v))
}

// CustomReasonLTE applies the LTE predicate on the "custom_reason" field.
func CustomReasonLTE(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLTE(FieldCustomReason, v))
}

// CustomReasonContains applies the Contains predicate on the "custom_reason" field.
func CustomReasonContains(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldContains(FieldCustomReason, v))
}

// CustomReasonHasPrefix applies the HasPrefix predicate on the "custom_reason" field.
func CustomReasonHasPrefix(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldHasPrefix(FieldCustomReason, v))
}

// CustomReasonHasSuffix applies the HasSuffix predicate on the "custom_reason" field.
func CustomReasonHasSuffix(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldHasSuffix(FieldCustomReason, v))
}

// CustomReasonIsNil applies the IsNil predicate on the "custom_reason" field.
func CustomReasonIsNil() predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIsNull(FieldCustomReason))
}

// CustomReasonNotNil applies the NotNil predicate on the "custom_reason" field.
func CustomReasonNotNil() predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotNull(FieldCustomReason))
}

// CustomReasonEqualFold applies the EqualFold predicate on the "custom_reason" field.
func CustomReasonEqualFold(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEqualFold(FieldCustomReason, v))
}

// CustomReasonContainsFold applies the ContainsFold predicate on the "custom_reason" field.
func CustomReasonContainsFold(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldContainsFold(FieldCustomReason, v))
}

// EffectiveDateEQ applies the EQ predicate on the "effective_date" field.
func EffectiveDateEQ(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldEffectiveDate, v))
}

// EffectiveDateNEQ applies the NEQ predicate on the "effective_date" field.
func EffectiveDateNEQ(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNEQ(FieldEffectiveDate, v))
}

// EffectiveDateIn applies the In predicate on the "effective_date" field.
func EffectiveDateIn(vs ...time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIn(FieldEffectiveDate, vs...))
}

// EffectiveDateNotIn applies the NotIn predicate on the "effective_date" field.
func EffectiveDateNotIn(vs ...time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotIn(FieldEffectiveDate, vs...))
}

// EffectiveDateGT applies the GT predicate on the "effective_date" field.
func EffectiveDateGT(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGT(FieldEffectiveDate, v))
}

// EffectiveDateGTE applies the GTE predicate on the "effective_date" field.
func EffectiveDateGTE(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGTE(FieldEffectiveDate, v))
}

// EffectiveDateLT applies the LT predicate on the "effective_date" field.
func EffectiveDateLT(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLT(FieldEffectiveDate, v))
}

// EffectiveDateLTE applies the LTE predicate on the "effective_date" field.
func EffectiveDateLTE(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLTE(FieldEffectiveDate, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldContainsFold(FieldNotes, v))
}

// ReactivatedAtEQ applies the EQ predicate on the "reactivated_at" field.
func ReactivatedAtEQ(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldEQ(FieldReactivatedAt, v))
}

// ReactivatedAtNEQ applies the NEQ predicate on the "reactivated_at" field.
func ReactivatedAtNEQ(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNEQ(FieldReactivatedAt, v))
}

// ReactivatedAtIn applies the In predicate on the "reactivated_at" field.
func ReactivatedAtIn(vs ...time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIn(FieldReactivatedAt, vs...))
}

// ReactivatedAtNotIn applies the NotIn predicate on the "reactivated_at" field.
func ReactivatedAtNotIn(vs ...time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotIn(FieldReactivatedAt, vs...))
}

// ReactivatedAtGT applies the GT predicate on the "reactivated_at" field.
func ReactivatedAtGT(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGT(FieldReactivatedAt, v))
}

// ReactivatedAtGTE applies the GTE predicate on the "reactivated_at" field.
func ReactivatedAtGTE(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldGTE(FieldReactivatedAt, v))
}

// ReactivatedAtLT applies the LT predicate on the "reactivated_at" field.
func ReactivatedAtLT(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLT(FieldReactivatedAt, v))
}

// ReactivatedAtLTE applies the LTE predicate on the "reactivated_at" field.
func ReactivatedAtLTE(v time.Time) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldLTE(FieldReactivatedAt, v))
}

// ReactivatedAtIsNil applies the IsNil predicate on the "reactivated_at" field.
func ReactivatedAtIsNil() predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldIsNull(FieldReactivatedAt))
}

// ReactivatedAtNotNil applies the NotNil predicate on the "reactivated_at" field.
func ReactivatedAtNotNil() predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.FieldNotNull(FieldReactivatedAt))
}

// HasEntity applies the HasEdge predicate on the "entity" edge.
func HasEntity() predicate.EntityOffboarding {
	return predicate.EntityOffboarding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EntityTable, EntityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEntityWith applies the HasEdge predicate on the "entity" edge with a given conditions (other predicates).
func HasEntityWith(preds ...predicate.Entity) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(func(s *sql.Selector) {
		step := newEntityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.EntityOffboarding) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.EntityOffboarding) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.EntityOffboarding) predicate.EntityOffboarding {
	return predicate.EntityOffboarding(sql.NotPredicates(p))
}
