// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entityoffboarding"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/predicate"
)

// EntityOffboardingUpdate is the builder for updating EntityOffboarding entities.
type EntityOffboardingUpdate struct {
	config
	hooks    []Hook
	mutation *EntityOffboardingMutation
}

// Where appends a list predicates to the EntityOffboardingUpdate builder.
func (_u *EntityOffboardingUpdate) Where(ps ...predicate.EntityOffboarding) *EntityOffboardingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntityOffboardingUpdate) SetUpdatedAt(v time.Time) *EntityOffboardingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetReactivatedAt sets the "reactivated_at" field.
func (_u *EntityOffboardingUpdate) SetReactivatedAt(v time.Time) *EntityOffboardingUpdate {
	_u.mutation.SetReactivatedAt(v)
	return _u
}

// SetNillableReactivatedAt sets the "reactivated_at" field if the given value is not nil.
func (_u *EntityOffboardingUpdate) SetNillableReactivatedAt(v *time.Time) *EntityOffboardingUpdate {
	if v != nil {
		_u.SetReactivatedAt(*v)
	}
	return _u
}

// ClearReactivatedAt clears the value of the "reactivated_at" field.
func (_u *EntityOffboardingUpdate) ClearReactivatedAt() *EntityOffboardingUpdate {
	_u.mutation.ClearReactivatedAt()
	return _u
}

// Mutation returns the EntityOffboardingMutation object of the builder.
func (_u *EntityOffboardingUpdate) Mutation() *EntityOffboardingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EntityOffboardingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityOffboardingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EntityOffboardingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityOffboardingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityOffboardingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entityoffboarding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityOffboardingUpdate) check() error {
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityOffboarding.entity"`)
	}
	return nil
}

func (_u *EntityOffboardingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entityoffboarding.Table, entityoffboarding.Columns, sqlgraph.NewFieldSpec(entityoffboarding.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entityoffboarding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CustomReasonCleared() {
		_spec.ClearField(entityoffboarding.FieldCustomReason, field.TypeString)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(entityoffboarding.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ReactivatedAt(); ok {
		_spec.SetField(entityoffboarding.FieldReactivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReactivatedAtCleared() {
		_spec.ClearField(entityoffboarding.FieldReactivatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entityoffboarding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EntityOffboardingUpdateOne is the builder for updating a single EntityOffboarding entity.
type EntityOffboardingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EntityOffboardingMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EntityOffboardingUpdateOne) SetUpdatedAt(v time.Time) *EntityOffboardingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetReactivatedAt sets the "reactivated_at" field.
func (_u *EntityOffboardingUpdateOne) SetReactivatedAt(v time.Time) *EntityOffboardingUpdateOne {
	_u.mutation.SetReactivatedAt(v)
	return _u
}

// SetNillableReactivatedAt sets the "reactivated_at" field if the given value is not nil.
func (_u *EntityOffboardingUpdateOne) SetNillableReactivatedAt(v *time.Time) *EntityOffboardingUpdateOne {
	if v != nil {
		_u.SetReactivatedAt(*v)
	}
	return _u
}

// ClearReactivatedAt clears the value of the "reactivated_at" field.
func (_u *EntityOffboardingUpdateOne) ClearReactivatedAt() *EntityOffboardingUpdateOne {
	_u.mutation.ClearReactivatedAt()
	return _u
}

// Mutation returns the EntityOffboardingMutation object of the builder.
func (_u *EntityOffboardingUpdateOne) Mutation() *EntityOffboardingMutation {
	return _u.mutation
}

// Where appends a list predicates to the EntityOffboardingUpdate builder.
func (_u *EntityOffboardingUpdateOne) Where(ps ...predicate.EntityOffboarding) *EntityOffboardingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EntityOffboardingUpdateOne) Select(field string, fields ...string) *EntityOffboardingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EntityOffboarding entity.
func (_u *EntityOffboardingUpdateOne) Save(ctx context.Context) (*EntityOffboarding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EntityOffboardingUpdateOne) SaveX(ctx context.Context) *EntityOffboarding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EntityOffboardingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EntityOffboardingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EntityOffboardingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := entityoffboarding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EntityOffboardingUpdateOne) check() error {
	if _u.mutation.EntityCleared() && len(_u.mutation.EntityIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EntityOffboarding.entity"`)
	}
	return nil
}

func (_u *EntityOffboardingUpdateOne) sqlSave(ctx context.Context) (_node *EntityOffboarding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(entityoffboarding.Table, entityoffboarding.Columns, sqlgraph.NewFieldSpec(entityoffboarding.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EntityOffboarding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, entityoffboarding.FieldID)
		for _, f := range fields {
			if !entityoffboarding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != entityoffboarding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(entityoffboarding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.CustomReasonCleared() {
		_spec.ClearField(entityoffboarding.FieldCustomReason, field.TypeString)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(entityoffboarding.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.ReactivatedAt(); ok {
		_spec.SetField(entityoffboarding.FieldReactivatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReactivatedAtCleared() {
		_spec.ClearField(entityoffboarding.FieldReactivatedAt, field.TypeTime)
	}
	_node = &EntityOffboarding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{entityoffboarding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
