// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entity"
	"github.com/sysadminsmedia/homebox/backend/internal/data/ent/entityoffboarding"
)

// EntityOffboarding is the model entity for the EntityOffboarding schema.
type EntityOffboarding struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// EntityID holds the value of the "entity_id" field.
	EntityID uuid.UUID `json:"entity_id,omitempty"`
	// Outcome holds the value of the "outcome" field.
	Outcome entityoffboarding.Outcome `json:"outcome,omitempty"`
	// CustomReason holds the value of the "custom_reason" field.
	CustomReason string `json:"custom_reason,omitempty"`
	// EffectiveDate holds the value of the "effective_date" field.
	EffectiveDate time.Time `json:"effective_date,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// ReactivatedAt holds the value of the "reactivated_at" field.
	ReactivatedAt *time.Time `json:"reactivated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EntityOffboardingQuery when eager-loading is set.
	Edges        EntityOffboardingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EntityOffboardingEdges holds the relations/edges for other nodes in the graph.
type EntityOffboardingEdges struct {
	// Entity holds the value of the entity edge.
	Entity *Entity `json:"entity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EntityOrErr returns the Entity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EntityOffboardingEdges) EntityOrErr() (*Entity, error) {
	if e.Entity != nil {
		return e.Entity, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: entity.Label}
	}
	return nil, &NotLoadedError{edge: "entity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EntityOffboarding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case entityoffboarding.FieldOutcome, entityoffboarding.FieldCustomReason, entityoffboarding.FieldNotes:
			values[i] = new(sql.NullString)
		case entityoffboarding.FieldCreatedAt, entityoffboarding.FieldUpdatedAt, entityoffboarding.FieldEffectiveDate, entityoffboarding.FieldReactivatedAt:
			values[i] = new(sql.NullTime)
		case entityoffboarding.FieldID, entityoffboarding.FieldEntityID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EntityOffboarding fields.
func (_m *EntityOffboarding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case entityoffboarding.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case entityoffboarding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case entityoffboarding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case entityoffboarding.FieldEntityID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value != nil {
				_m.EntityID = *value
			}
		case entityoffboarding.FieldOutcome:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field outcome", values[i])
			} else if value.Valid {
				_m.Outcome = entityoffboarding.Outcome(value.String)
			}
		case entityoffboarding.FieldCustomReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field custom_reason", values[i])
			} else if value.Valid {
				_m.CustomReason = value.String
			}
		case entityoffboarding.FieldEffectiveDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_date", values[i])
			} else if value.Valid {
				_m.EffectiveDate = value.Time
			}
		case entityoffboarding.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case entityoffboarding.FieldReactivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reactivated_at", values[i])
			} else if value.Valid {
				_m.ReactivatedAt = new(time.Time)
				*_m.ReactivatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the EntityOffboarding.
// This includes values selected through modifiers, order, etc.
func (_m *EntityOffboarding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEntity queries the "entity" edge of the EntityOffboarding entity.
func (_m *EntityOffboarding) QueryEntity() *EntityQuery {
	return NewEntityOffboardingClient(_m.config).QueryEntity(_m)
}

// Update returns a builder for updating this EntityOffboarding.
// Note that you need to call EntityOffboarding.Unwrap() before calling this method if this EntityOffboarding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EntityOffboarding) Update() *EntityOffboardingUpdateOne {
	return NewEntityOffboardingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EntityOffboarding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EntityOffboarding) Unwrap() *EntityOffboarding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: EntityOffboarding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EntityOffboarding) String() string {
	var builder strings.Builder
	builder.WriteString("EntityOffboarding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("entity_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EntityID))
	builder.WriteString(", ")
	builder.WriteString("outcome=")
	builder.WriteString(fmt.Sprintf("%v", _m.Outcome))
	builder.WriteString(", ")
	builder.WriteString("custom_reason=")
	builder.WriteString(_m.CustomReason)
	builder.WriteString(", ")
	builder.WriteString("effective_date=")
	builder.WriteString(_m.EffectiveDate.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	if v := _m.ReactivatedAt; v != nil {
		builder.WriteString("reactivated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// EntityOffboardings is a parsable slice of EntityOffboarding.
type EntityOffboardings []*EntityOffboarding
